apiVersion: 1
prune: true

datasources:
  - name: Postgres
    uid: postgres

    type: postgres
    access: proxy
    url: postgres:5432

    user: postgres_ro
    jsonData:
      database: postgres
      sslmode: disable
    secureJsonData:
      password: postgres_ro

    version: 1
    editable: false

  - name: Speedtest
    uid: speedtest

    type: postgres
    access: proxy
    url: postgres:5432

    user: postgres_ro
    jsonData:
      database: speedtest
      sslmode: disable
    secureJsonData:
      password: postgres_ro

    version: 1
    editable: false
