services:
    grafana:
        container_name: grafana
        user: '0'
        ports:
            - '8080:3000'
        volumes:
            - './data:/var/lib/grafana'
            - './conf:/etc/grafana/provisioning'
        environment:
            - 'GF_SECURITY_ADMIN_EMAIL=admin@localhost'
            - 'GF_SECURITY_ADMIN_USERNAME=admin'
            - 'GF_SECURITY_ADMIN_PASSWORD=password'
        image: 'grafana/grafana:latest'
        restart: unless-stopped
        networks:
            - home-automation

networks:
    home-automation:
        driver: bridge
        name: home-automation
