services:
    smokeping:
        container_name: smokeping
        hostname: smokeping
        ports:
            - '8082:80'
        volumes:
            - './conf:/config'
            - './data:/data'
        environment:
            - 'TZ=Europe/London'
        image: 'lscr.io/linuxserver/smokeping:latest'
        restart: unless-stopped

    smokeping-rrd:
        container_name: smokeping-rrd
        hostname: smokeping-rrd
        volumes:
            - './data:/data'
        build:
            context: https://github.com/doublemarket/grafana-rrd-server.git
        entrypoint: ["/grafana-rrd-server", "-r", "/data"]
        restart: unless-stopped
        networks:
            - home-automation

networks:
    home-automation:
        driver: bridge
        name: home-automation
