services:
    postgres:
        container_name: postgres
        command: postgres -c 'config_file=/etc/postgresql/postgresql.conf'
        ports:
            - '5432:5432'
        volumes:
            - './data:/var/lib/postgresql/data'
            - './conf/postgresql.conf:/etc/postgresql/postgresql.conf'
            - './conf/entrypoint.sh:/docker-entrypoint-initdb.d/entrypoint.sh'
        environment:
            - 'POSTGRES_USER=postgres'
            - 'POSTGRES_PASSWORD=postgres'
            - 'PGDATA=/var/lib/postgresql/data'
        image: 'postgres:latest'
        restart: unless-stopped
        networks:
            - home-automation

networks:
    home-automation:
        driver: bridge
        name: home-automation
